### ISSUE TITLE
FR: Option to filter out `serverless-plugin-warmup` invocations

### ISSUE THREAD

**Issue by r-token** [serverless/console#59]
I asked this question in the community call earlier today and was advised to follow up in a more concrete capacity. If this question is better suited as a discussion elsewhere, let me know!

We use [`serverless-plugin-warmup`](https://www.npmjs.com/package/serverless-plugin-warmup) for several of our functions. The warmup invocations fire every `x` minutes, and thus fill the invocations dashboard with noise we don't care much about.

It would be fantastic if there was an option to filter out function invocations that were triggered by the warmup event (and potentially other popular events as well).

**Comment by hev** [comment]
@r-token thanks for submitting. I don't think we'll accomodate a specific plugin filter in Console, but I'd imagine you could use service or other filtering mechanisms to isolate away these requests. Its worth looking at the trace to see what specific details it has.
